
# Loads default set of integrations. Do not remove.
default_config:

# https://www.home-assistant.io/integrations/homeassistant/
homeassistant:
  debug: true



logger:
  default: info
  logs:
    custom_components.stiebel_eltron_isg: debug


